Profile Picture Toast
AltCamp/altcampv1-frontend pull request #206
Opened 2023-07-05 21:22 UTC by just-talis

This PR...

## Changes

-

## Fixes
-

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [x] added/updated a component
- [ ] fixed a bug
- [ ] added/updated a new route
- [ ] added or changed css styles

Fixes #

2023-07-05 21:24 UTC, vader-js approved these changes

2023-07-05 21:26 UTC, Boye95 requested changes
@just-talis Please go through the CONTRIBUTION.md file to see how to write PR titles. Thanks

2023-07-06 06:03 UTC, Boye95 approved these changes
Thanks

2023-07-06 14:16 UTC, Yinkajay approved these changes

2023-07-07 08:37 UTC, merged